### ISSUE TITLE
Is this still being maintained? 

### ISSUE THREAD

**Issue by Cobular** [strongback/strongback-java#118]

**Comment by andrewda** [comment]
Considering the last commit was about two years ago, my guess is no. It would likely require quite a few significant changes to get Strongback working with the 2019 version of WPILib. There are, however, many similar libraries that are being actively maintained this year:

- https://github.com/TeamMeanMachine/meanlib
- https://github.com/ezAuton/ezAuton
- https://github.com/DurhamAcademy/kyberlib
- https://github.com/sertain/sertain
- https://github.com/team401/SnakeSkin
- https://github.com/5190GreenHopeRobotics/FalconLibrary
- Many more I'm likely forgetting about or haven't looked into much yet

**Comment by Cobular** [comment]
@andewda, thanks for ur response. Sorry I didn't see it until now! I'll check those out for next season.
