### ISSUE TITLE
Typo In Document Example

### ISSUE THREAD

**Issue by jrutten** [strongback/strongback-java#57]
https://strongback.gitbooks.io/using-strongback/content/using_commands.html

The 4th example under "Using CommandGroup" is:

```
public MyForkCommands() {
    sequentially(new CommandA(),
                 new CommandB(),
                 fork(new Command C()),
                 new CommandD());
                 new sequentially( new CommandE(), new CommandF()));
}
```

The surrounding text implies that E and F commands should be in "simultaneously(...)", not a "new sequentially(...)".

**Comment by rhauch** [comment]
@jrutten: thanks! It is fixed.
