### ISSUE TITLE
Turning Tank Drive Robot a certain angle

### ISSUE THREAD

**Issue by maskedband1t** [strongback/strongback-java#59]
Sorry if this is not an "issue" per say, but I did not know where to post this question, and the replies on this page tend to be quick, which is my priority. How can you make a drivetrain in tank turn a certain angle from its previous point on its own radius? For example, if my robot is facing forward, is there anyway to get it turn say, 15 degrees clockwise, when I give it a command of MoveAngle(15);? This is all obviously in terms of Strongback.

examples would be greatly appreciated.

**Comment by rhauch** [comment]
The proper place to ask is on our [discussion forum](https://groups.google.com/forum/#!forum/strongback).
