### ISSUE TITLE
TalonSRX seems to swap forward/reverse limit switches?

### ISSUE THREAD

**Issue by agausmann** [strongback/strongback-java#64]
Should this be fixed? It may cause a lot of confusion with others (it did for me)

In `org.strongback.hardware.HardwareTalonSRX`:

```
    HardwareTalonSRX( ... ) {
        ...
        this.forwardLimitSwitch = talon::isRevLimitSwitchClosed;
        this.reverseLimitSwitch = talon::isFwdLimitSwitchClosed;
        ...
    }
```

**Comment by rhauch** [comment]
Yes, it probably should be fixed. But I'm hesitant to change the behavior at this point in time since it would break existing code that might already have corrected for the error. Thoughts?

**Comment by agausmann** [comment]
It should be postponed at least until the next minor release (1.2) and the change should be explicitly noted in the release notes. It shouldn't be released as a patch because it silently changes the behavior of the code.

Let's perform the fix now and merge/tag it post-season.
