### ISSUE TITLE
Autonomous doesn't switch to Teleop?

### ISSUE THREAD

**Issue by niharmitra** [strongback/strongback-java#77]
After we run a command group in autonomous, we end up not being able to start our teleop commands unless we run killAllCommands in teleopInit(). What could be causing this, and what is the correct solution (if not killAllCommands)?

**Comment by rhauch** [comment]
If your command does not stop or timeout, then you will have to call the `killAllCommands` as you mention. Ideally, your command should finish naturally, but there's no harm in killing them. Another option is to call `Strongback.restart()` in `teleopInit()`, which kills commands and cleans up a few other things. Either way works. 

IOW, this is not an issue with Strongback, but could bean issue with your particular commands.
