### ISSUE TITLE
Mock solenoids 

### ISSUE THREAD

**Issue by FilipKernan** [strongback/strongback-java#86]
The instantaneousSolenoid() method and the manualSolenoid() return essentially the same object.  From what I have gathered from the code is that the manualSolenoid() should be set to false.
`/**
     * Create a solenoid that operates instantaneously and immediately stops.
     *
     * @return the mock solenoid; never null
     */
    public static MockSolenoid instantaneousSolenoid() {
        return new MockSolenoid(true);
    }

    /**
     * Create a solenoid that operates infinitely slowly and must be manually {@link MockSolenoid#stop() stopped}.
     *
     * @return the mock solenoid; never null
     */
    public static MockSolenoid manualSolenoid() {
        return new MockSolenoid(true);
    }`

**Comment by rhauch** [comment]
@FilipKernan, yeah, I think you're right. The `manualSolenoid` method should call `new MockSolenoid(false);`. Do you want to submit a pull request? (If so, please feel free to add your name to the `CONTRIBUTORS` file in the root of the repository in a second commit within the same pull request.)

**Comment by FilipKernan** [comment]
@rhauch sure. Will do.

**Comment by rhauch** [comment]
Fixed by #87
